# Generated by Django 3.1.3 on 2020-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('studid', models.IntegerField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('bdate', models.DateField()),
                ('placebirth', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=50, null=True)),
                ('subname', models.CharField(max_length=200, null=True)),
                ('lec', models.FloatField()),
                ('lab', models.FloatField()),
                ('unit', models.FloatField()),
                ('sched', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
