# Generated by Django 3.1.3 on 2020-11-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('studid', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Acitive'), ('Offline', 'Offline'), ('Do Not Disturb', 'Do not Disturb'), ('Idle', 'Idle')], max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('bdate', models.DateField()),
                ('placebirth', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_backend.profsubject')),
            ],
        ),
        migrations.CreateModel(
            name='StudGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studgrades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_backend.grades')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_backend.schoolworks')),
            ],
        ),
    ]
