# Generated by Django 3.1.3 on 2020-11-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_backend', '0002_auto_20201119_0404'),
        ('student_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Acitive'), ('Offline', 'Offline'), ('Do Not Disturb', 'Do not Disturb'), ('Idle', 'Idle')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StudGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studgrades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_backend.grades')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_backend.schoolworks')),
            ],
        ),
    ]
