# Generated by Django 3.1.3 on 2020-11-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_backend', '0002_auto_20201119_0404'),
        ('student_backend', '0002_auto_20201119_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studgrades',
            name='studgrades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_backend.grades'),
        ),
    ]
