# Generated by Django 3.1.3 on 2020-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('numofstud', models.IntegerField()),
                ('contactno', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('bdate', models.DateField()),
                ('placebirth', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schoolworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolwork', models.CharField(choices=[('As', 'Assignments'), ('Qu', 'Quiz'), ('Ac', 'Activities'), ('Pr', 'Projects')], max_length=2)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
