# Generated by Django 3.1.3 on 2020-11-19 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='professprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Acitive'), ('Offline', 'Offline'), ('Do Not Disturb', 'Do not Disturb'), ('Idle', 'Idle')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolworks',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professprofile',
            name='contactno',
            field=models.IntegerField(),
        ),
    ]
