# Generated by Django 3.1.3 on 2020-11-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_backend', '0002_auto_20201122_0548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sched',
            new_name='Schedule',
        ),
        migrations.AddField(
            model_name='profsubject',
            name='schedule',
            field=models.ManyToManyField(to='teacher_backend.Schedule'),
        ),
    ]
