# Generated by Django 3.1.3 on 2020-11-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_backend', '0003_auto_20201122_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profsubject',
            name='lab',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='profsubject',
            name='lec',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='profsubject',
            name='unit',
            field=models.FloatField(max_length=3),
        ),
    ]
